
pub const MEMORY_ADDRESS_START: u16 = 0x0000;
pub const MEMORY_ADDRESS_END: u16 = 0xFFFF;
pub const MEMORY_ADDRESS_ZERO_PAGE_START: u16 = MEMORY_ADDRESS_START;
pub const MEMORY_ADDRESS_ZERO_PAGE_END: u16 = 0x00FF;
pub const MEMORY_ADDRESS_STACK_START: u16 = 0x0100;
pub const MEMORY_ADDRESS_STACK_END: u16 = 0x01FF;
pub const MEMORY_ADDRESS_RAM_START: u16 = 0x0200;
pub const MEMORY_ADDRESS_RAM_END: u16 = 0xFFFF;
